config/routes.rb
Couplify::Application.routes.draw do
  devise_for :users

  resources :invites, :only => [:create, :new, :update, :destroy] do
    get "waiting", :on => :member
    get "make_decision", :on => :collection
  end
  
  resources :couples, :only => [:create, :update] do
    member do
      resources :posts, :only => [:index]
    end
    collection do
      put ":profile_name/update_posts", :to => "posts#update_posts"
      get ":profile_name/add_posts", :to => "posts#new", :as => :new_posts
      post ":profile_name/posts", :to => "posts#create", :as => :add_posts
      get ":profile_name", :to => "couples#profile", :as => :profile
      get ":profile_name/edit", :to => "couples#edit", :as => :edit_profile
    end
  end
  
  resource :incoming_email, :only => [:create]
  resources :posts, :only => [:destroy, :update, :edit]
  root :to => "static_pages#home"
end

# resource routing and non-resourceful routes

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :accept_invitation, :p_email, :user_id, :waiting, :message
  
  # need to add custom error messages
  validates :p_email, :user_id, :presence => true
  validates :user_id, :uniqueness => true
  validate :invitee_does_not_have_couplify_profile
  
  belongs_to :user
  
  def invitee_does_not_have_couplify_profile
    invitee = User.find_by_email(self.p_email)
    if invitee && Couple.user_has_profile?(invitee.id)
      errors[:base] << "The person you want to invite already has a Couplify page."
    end
  end
  
  def self.has_current_invitation?(user)
    @invites = Invite.where("p_email = ? AND waiting = ?", user.email, true)
    (@invites.empty?)? false : true
  end
  
  def reject_other_invitations
    @invitations = Invite.where(:p_email => self.p_email)
    @invitations.each do |invite|
      invite.waiting = false
      invite.accept_invitation = false
      invite.save
    end
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_filter :authenticate_user!
  
  def new
    @invite = Invite.new
  end
  
  def create
    params[:invite][:user_id] = current_user.id
    @invite = Invite.new(params[:invite])
    if current_user.email == params[:invite][:p_email]
      flash[:notice] = "You can't invite yourself."
      render 'new'
      return
    end
    if @invite.save
      # send an email to the partner
      @msg = InviteEmailMailer.invite_email(@invite)
      @msg.deliver!
      redirect_to waiting_invite_url(@invite)
    else
      flash.now[:errors] = @invite.errors.full_messages
      render 'new'
    end
  end
  
  def waiting
    @invite = Invite.find(params[:id])
    render 'waiting'
  end
  
  def make_decision
    has_current_invitation = Invite.has_current_invitation?(current_user)
    if has_current_invitation
      @invites = Invite.where(:p_email => current_user.email)
      render 'make_decision'
    else
      redirect_to new_invite_url
    end
  end
  
  def update
    @invite = Invite.find(params[:id])
    params[:invite][:waiting] = false
    if @invite.update_attributes(params[:invite])
      # email inviter about the acceptance?
      if @invite.accept_invitation
        # reject other invitations
        @invite.reject_other_invitations
        
        @couple = Couple.create_couple(@invite.user_id, current_user.id)
        if @couple.save
          redirect_to "#{root_url}couples/#{@couple.profile_name}"
        else
          render :text => "something is wrong"
        end
      else
        redirect_to new_invite_url
      end
    else
      redirect_to new_invite_url
    end
    
  end
  
  def destroy
    @invite = Invite.find(params[:id])
    @invite.destroy
    redirect_to new_invite_url
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/make_decision.html.erb
<div class="col-xs-9 col-xs-offset-2">
  <div class="row" style="padding-top: 100px;">
  <% @invites.each do |invite| %>
    <% inviter = User.find(invite.user_id) %>
    <h3><%= inviter.first_name %> <%= inviter.last_name %> has invited you to have a Couplify profile together.</h3>

    <form action="<%= invite_url(invite) %>" method="POST" class="inline-form">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
      <input type="hidden" value="PUT" name="_method" />
      <input type="hidden" name="invite[accept_invitation]" value="true" />
      <button type="submit" class="btn btn-success" style="margin-right: 20px;">Accept</button>
    </form>

    <form action="<%= invite_url(invite) %>" method="POST" class="inline-form">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
      <input type="hidden" value="PUT" name="_method" />
      <input type="hidden" name="invite[accept_invitation]" value="false" />
      <button type="submit" class="btn btn-danger">Reject</button>
  </form>
  </div>  
  <% end %>
</div>

app/views/invites/new.html.erb
<div class="col-xs-6 col-xs-offset-2">
  <h2>Invite Your Partner</h2>
  <form action="<%= invites_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
    <div class="form-group">
      <label for="p_email">Partner's email address</label>
      <input type="text" name="invite[p_email]" id="p_email" class="form-control"
              value ="<%= @invite.p_email %>"/>
    </div>
    <div class="form-group">
      <label for="message">Message</label>
      <textarea type="text" id="message" class="form-control"
                name="invite[message]"/><%= @invite.message %></textarea>
    </div>
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>
</div>
<div class="col-xs-4"></div>

app/views/invites/waiting.html.erb
<div class="row" style="padding-top: 100px;">
  <h4 class="text-center">Hey <%= current_user.first_name.capitalize %>, you are still waiting for <%= @invite.p_email %>'s repsonse.</h4>
  <br />
  <div class="col-xs-9 col-xs-offset-3">

    <img src="/assets/cuplify.jpg" alt="" id="partner" class="profile-img"/>
    <img src="/assets/loading.gif" alt="" id="loading"/>
    <br />
    <br />
    <%= button_to("Cancel this invitation", invite_url(@invite), {:method => :delete,  :class => "btn btn-primary"})%>
  </div>  
</div>