config/routes.rb
Couplify::Application.routes.draw do
  devise_for :users

  resources :invites, :only => [:create, :new, :update, :destroy] do
    get "waiting", :on => :member
    get "make_decision", :on => :collection
  end
  
  resources :couples, :only => [:create, :update] do
    member do
      resources :posts, :only => [:index]
    end
    collection do
      put ":profile_name/update_posts", :to => "posts#update_posts"
      get ":profile_name/add_posts", :to => "posts#new", :as => :new_posts
      post ":profile_name/posts", :to => "posts#create", :as => :add_posts
      get ":profile_name", :to => "couples#profile", :as => :profile
      get ":profile_name/edit", :to => "couples#edit", :as => :edit_profile
    end
  end
  
  resource :incoming_email, :only => [:create]
  resources :posts, :only => [:destroy, :update, :edit]
  root :to => "static_pages#home"
end

# resource routing and non-resourceful routes

app/models/couple.rb
class Couple < ActiveRecord::Base
  attr_accessible :anniversary_date, :profile_name, :u1_id, :u2_id
  
  validates :profile_name, :uniqueness => true, :presence => true
  validates :u1_id, :u2_id, :anniversary_date, :presence => true
  
  belongs_to :u1, :class_name => "User", :primary_key => :id, :foreign_key => :u1_id
  belongs_to :u2, :class_name => "User", :primary_key => :id, :foreign_key => :u2_id
  
  has_many :posts
  
  def self.create_couple(inviter_id, invitee_id)
    Couple.new({:u1_id => inviter_id, :u2_id => invitee_id, 
                          :profile_name => Time.now.to_i.to_s })
  end
  
  def self.user_has_profile?(user_id)
    @couples = Couple.where("u1_id = ? OR u2_id = ?", user_id, user_id)
    (@couples.empty?)? false : true
  end
  
  def self.get_couple_id(email)
    email = Mail::Address.new(email).address
    return nil unless email =~ /@couplify.me$/
    profile_name = email.gsub(/@couplify.me$/, "")
    if profile_name == "sf"
      couple = Couple.find_by_profile_name("sf")
    else
      couple = Couple.find_by_profile_name(profile_name)
    end
    return (couple.nil?)? nil : couple.id
  end
  
  def is_sender_owner?(sender_id)
    if sender_id == self.u1_id || sender_id == self.u2_id
      return true
    end
    return false
  end
  
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :current_user_owns_profile!, :only => [:profile]
  
  def profile
    @couple = Couple.find_by_profile_name(params[:profile_name])
    @posts_data = @couple.posts.page(1).per(20).includes(:owner)
                               .order('created_at DESC').to_json(:methods => [:image_url]).html_safe 
    @u1 = User.find(@couple.u1_id)
    @u2 = User.find(@couple.u2_id)
    @num_posts = @couple.posts.count
    if current_user.email == "couplify.one@gmail.com"
      # demo account
      flash[:notice] = "You are signed in through a guest account."
    end
    render 'profile'
  end
  
  
  def update
    @couple = Couple.find(params[:id])
    if @couple.update_attributes(params[:couple])
      print "#{root_url}couples/#{@couple.profile_name}"
      redirect_to "/couples/#{@couple.profile_name}"
    else
      @errors = @couple.errors.full_messages
      render 'edit'
    end
  end
  
  def edit
    @couple = Couple.find_by_profile_name(params[:profile_name])
  end
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/views/couples/edit.html.erb
<div class="col-xs-6 col-xs-offset-2">
<h2>Edit Couplify Profile</h2>
<form action="<%= couple_url(@couple) %>" role="form" id="edit-couple-form" method="POST">
  <input type="hidden" name="_method" value="PUT"/> <!-- _method = put? -->
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <input type="hidden" id="old_profile_name" name="old_profile_name" value="<%= @couple.profile_name %>" />
  <div class="form-group">
    <label for="anniversary-date" class="control-label">Anniversary</label>    
    <input type="date" class="form-control" id="modal-anniversary-date"
            name="couple[anniversary_date]" value="<%= @couple.anniversary_date %>" />
    
  </div>
  <div class="form-group" id="profile-name-form-div">
    <label for="profile-name" class="control-label">Profile name/Couplify email</label>
    <input type="text" class="form-control" id="modal-profile-name"
              name="couple[profile_name]" value="<%= @couple.profile_name %>" />
  </div>
  <% if  @errors %>
    <div class="form-group" id="profile-name-error-div">
      <% @errors.each do |error| %>
        <p><%= error %></p>
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <button type="submit" class="btn btn-primary" id="submit-couple-edit">Save Changes</button>
  </div>
</form>
</div>

app/views/couples/profile.html.erb
<div class="row" id="profile-cover">
  <div class="wrapper">
    <img src="/assets/cover-photo.jpg" alt="" id="cover-photo"/>
    <div class="box" style="padding-top: 20px;">
      <%= image_tag @u1.profile_image.url(:medium), :class => "user-profile-img" %>
      <img src="/assets/heart-shadow.jpg" alt="" id=""/>
      <h2><%= @u1.first_name.capitalize %></h2>
    </div>
    <div class="box">
      <img src="/assets/red-heart-icon.png" alt="" id="heart-profile-info"/>
      <div id="profile-info">
        <p>Email: <br /><span id="profile-name"><%= @couple.profile_name %>@couplify.me</span> <span class="glyphicon glyphicon-info-sign info-tooltip" id="email-info" data-placement="bottom" data-toggle="tooltip" title="Write your message in the subject line and send it to this email address to create a post" ></span></p>
        <p>Anniversary: <br /><span id="anniversary-date"><%= @couple.anniversary_date %></span></p>
      </div>
  
      <button data-toggle="tooltip" title="To be implemented" class="btn btn-primary info-tooltip" id="export-btn">Export Profile as PDF</button>
    </div>
    <div class="box" style="padding-top: 20px;">
      <%= image_tag @u2.profile_image.url(:medium), :class => "user-profile-img" %>
      <img src="/assets/heart-shadow.jpg" alt="" id=""/>
      <h2><%= @u2.first_name.capitalize %></h2>
    </div>
  </div>  
</div>

<div class="row">
  <div id="posts-div"></div>
</div>


<script type="text/template" id="posts-template">
  <%% _(posts).each(function(post){ %>
    <%%= renderSubPost({post: post}) %>
  <%% }); %>
</script>

<script type="text/template" id="post-template">
  <div class="post">
    <button class="delete-post close text-right" data-id="<%%= post.id %>" style="margin: 0px 5px 0px 5px;">&times;</button>
    <a href="/posts/<%%= post.id %>/edit" style="padding-top: 1px; float: right;">Edit</a>
    <div class="author-info">
      <%% if (Couplify.u1.id == post.user_id) { %>
        <img src="<%%= Couplify.u1.profile_image_url %>" alt="<%%= Couplify.u1.first_name %>" class="author-img" />
        <span class="text-left author-name"><%%= Couplify.u1.first_name %></span>
      <%% }else if (Couplify.u2.id == post.user_id){ %>
        <img src="<%%= Couplify.u2.profile_image_url %>" alt="<%%= Couplify.u2.first_name %>" class="author-img" />
        <span class="text-left author-name"><%%= Couplify.u2.first_name %></span>
      <%% } %>
      <span class="post-time"><%%= (new Date(post.created_at)).toLocaleTimeString("en-us", Couplify.date_options) %></span>
    </div>
    <p class="divider"></p>
    <div class="post-body">
      <p><%%= post.body %></p>
    </div>
    <img src="<%%= post.image_url %>" alt="" />
  </div>
</script>

<script type="text/json" id="bootstrapped-posts-json">
  { "posts": <%= @posts_data %> }
</script>


<script type="text/javascript">
  Couplify.COUPLE_ID = <%= @couple.id %>;
  Couplify.u1 = <%= @u1.basic_info_in_json %>;
  Couplify.u2 = <%= @u2.basic_info_in_json %>;
  Couplify.u1["profile_image_url"] = "<%= @u1.profile_image.url(:thumb) %>";
  Couplify.u2["profile_image_url"] = "<%= @u2.profile_image.url(:thumb) %>";
  Couplify.NUM_POSTS = <%= @num_posts %>;
  Couplify.date_options = {
    weekday: "long", year: "numeric", month: "short",
    day: "numeric", hour: "2-digit", minute: "2-digit"
  }
  
</script>