config/routes.rb
Couplify::Application.routes.draw do
  devise_for :users

  resources :invites, :only => [:create, :new, :update, :destroy] do
    get "waiting", :on => :member
    get "make_decision", :on => :collection
  end
  
  resources :couples, :only => [:create, :update] do
    member do
      resources :posts, :only => [:index]
    end
    collection do
      put ":profile_name/update_posts", :to => "posts#update_posts"
      get ":profile_name/add_posts", :to => "posts#new", :as => :new_posts
      post ":profile_name/posts", :to => "posts#create", :as => :add_posts
      get ":profile_name", :to => "couples#profile", :as => :profile
      get ":profile_name/edit", :to => "couples#edit", :as => :edit_profile
    end
  end
  
  resource :incoming_email, :only => [:create]
  resources :posts, :only => [:destroy, :update, :edit]
  root :to => "static_pages#home"
end

# resource routing and non-resourceful routes

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :couple_id, :image, :user_id
  
  validates :user_id, :couple_id, :presence => true
  
  belongs_to :couple
  belongs_to :owner, :class_name => "User"
  
  has_attached_file :image, 
                    :styles => { :medium => "500x500>" }, 
                    :cover_options => {:all => '-auto-orient'}
  
  def image_url
    (self.image_file_name.nil?) ? nil : self.image.url
  end

  def include_image_link_json
    self.to_json(:methods => [:image_url]).html_safe
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :current_user_owns_profile!, :only => [:index]
  
  def index
    @couple = Couple.find(params[:id])
    @posts = @couple.posts.page(params[:page]).per(20).includes(:owner).order('created_at DESC')
    render :json => @posts.to_json(:methods => [:image_url]).html_safe
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    render :json => { :status => 200 }
  end
  
  def new
    @couple = Couple.find_by_profile_name(params[:profile_name])
  end
  
  def create
    @couple = Couple.find_by_profile_name(params[:profile_name])
    params[:post][:user_id] = current_user.id
    @post = @couple.posts.new(params[:post])
    if @post.save
      render :json => @post.include_image_link_json
    else
      render :json => {:status => :unprocessable_entitiy}
    end
  end
  
  def update_posts
    if Post.update(params[:posts].keys, params[:posts].values)
    else
      flash[:alert] = "Error saving your posts"  
    end
    redirect_to "/couples/#{params[:profile_name]}"
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
    else
      flash[:alert] = @post.errors.full_messages
    end
    redirect_to "/couples/#{current_user.couple.profile_name}"
  end
  
  def edit
    @post = Post.find(params[:id])
  end
end

app/views/posts/edit.html.erb
<div class="col-xs-6 col-xs-offset-2">
<h2>Edit Post</h2>
<form action="<%= post_url(@post) %>" role="form" id="" enctype="multipart/form-data" method="POST">
  <input type="hidden" name="_method" value="PUT"/>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  
  <div class="form-group">
    <textarea class="form-control" id=""
            name="post[body]" ><%= @post.body %></textarea>
  </div>
  <div class="form-group text-center" id="">
    <%= image_tag @post.image.url(:medium) %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary" id="submit-couple-edit">Save Changes</button>
  </div>
</form>
</div>

app/views/posts/new.html.erb
<div class="row">
  <br />
  <div id="upload-photo-div" >
    <form action="/couples/<%= @couple.profile_name %>/posts" method="POST" 
          enctype="multipart/form-data"
          class="" id="dropzone-form" >
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <div class="dz-default dz-message">
        <h2 class="text-center uploading" id="dz-instruction" >Drag and Drop files to upload picture</h2>
        <!-- <img src="/assets/loading.gif" alt="loading..." class="center hidden" id="uploading-image" style="padding: 30px;"/> -->
        <div class="progress progress-striped hidden uploading">
          <div class="progress-bar progress-bar-success" id="progress-bar" role="progressbar" style="width: 0%">
          </div>
        </div>
      </div>
      <br />
    </form>
    <form action="/couples/<%= @couple.profile_name %>/update_posts" method="POST" id="put-form" class="hidden">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
      <input type="hidden" name="_method" value="PUT" />
      <div id="preview-posts"></div>
      <div class="text-center" id="submit-btn-div">
        <button class="btn btn-primary btn-lg btn-block" type="submit" id="submit-btn">Save</button>
      </div>
    </form>
  </div>
  
</div>

<script type="text/template" id="preview-template">
  <div class="preview-post dz-preview">
     <span class="delete-preview">x</span>
     <input type="hidden" class="preview-post-id" name="posts[id]" value=""/>
     <div class="preview-post-body">
        <textarea rows="3" class="form-control preview-post-body-textarea" name="posts[body]" placeholder="your message" /></textarea>
     </div>
     <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
     <div class="dz-error-message"><span data-dz-errormessage></span></div>
     <img data-dz-thumbnail alt="" class="">
     <div class="dz-filename text-center"><span data-dz-name></span></div>
     <div class="dz-size text-center" data-dz-size></div>
  </div>
</script>